# Generated by Django 4.2.13 on 2026-04-20 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, choices=[('startup', '1–50'), ('small', '51–200'), ('medium', '201–1000'), ('large', '1001–5000'), ('enterprise', '5000+')], max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('glassdoor_rating', models.FloatField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('blacklisted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('jobs_found', models.IntegerField(default=0)),
                ('jobs_new', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='running', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('remote', models.BooleanField(default=False)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('experience_min', models.IntegerField(blank=True, null=True)),
                ('experience_max', models.IntegerField(blank=True, null=True)),
                ('skills_required', models.JSONField(default=list)),
                ('source', models.CharField(choices=[('linkedin', 'LinkedIn'), ('naukri', 'Naukri'), ('indeed', 'Indeed'), ('wellfound', 'Wellfound'), ('instahyre', 'Instahyre'), ('cutshort', 'Cutshort'), ('direct', 'Company Site'), ('referral', 'Referral')], max_length=20)),
                ('source_url', models.URLField(unique=True)),
                ('source_job_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('scored', 'AI Scored'), ('queued', 'In Queue'), ('applied', 'Applied'), ('viewed', 'Viewed by HR'), ('screening', 'Phone Screen'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='discovered', max_length=20)),
                ('ai_match_score', models.FloatField(blank=True, null=True)),
                ('ats_score', models.FloatField(blank=True, null=True)),
                ('description_embedding', pgvector.django.VectorField(blank=True, dimensions=384, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company')),
            ],
            options={
                'ordering': ['-ai_match_score', '-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume_version', models.CharField(blank=True, max_length=50)),
                ('cover_letter', models.TextField(blank=True)),
                ('custom_answers', models.JSONField(default=dict)),
                ('hr_email', models.EmailField(blank=True, max_length=254)),
                ('hr_name', models.CharField(blank=True, max_length=100)),
                ('outreach_sent', models.BooleanField(default=False)),
                ('outreach_sent_at', models.DateTimeField(blank=True, null=True)),
                ('outreach_reply_received', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['source'], name='jobs_job_source_e2155e_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['ai_match_score'], name='jobs_job_ai_matc_b5bc9a_idx'),
        ),
    ]
